// apps/hanerubeat/src/App.tsx
import { Global, css } from '@emotion/core'
import React, { FC } from 'react'
import Heartbeat from 'components/molecules/Heartbeat'

const globalStyles = css`
  body {
    background-color: #222;
    bottom: 0;
    left: 0;
    margin: 0;
    position: fixed;
    right: 0;
    top: 0;
  }

  #app {
    height: 100%;
  }
`

const App: FC = () => {
  return (
    <>
      <Global styles={globalStyles} />

      <Heartbeat />
    </>
  )
}

export default App

// apps/neru-camera/src/App.vue
<template>
  <div id="app">
    <RouterView />

    <link
      href="https://fonts.googleapis.com/css?family=Roboto:400"
      rel="stylesheet"
    />
  </div>
</template>

<script lang="ts">
import Vue from 'vue'

export default Vue.extend({
  name: 'App'
})
</script>

<style scoped>
#app {
  background-color: #1b1b1b;
  bottom: 0;
  font-family: Roboto, sans-serif;
  left: 0;
  position: fixed;
  right: 0;
  top: 0;
}
</style>
