// apps/neru-camera/src/app/camera/camera.component.ts
import { AfterViewInit, Component, ElementRef, ViewChild } from '@angular/core';
import { MatSnackBar } from '@angular/material';
import { environment } from '../../environments/environment';
import { CameraService } from './camera.service';

interface CanvasSize {
  height: number;
  width: number;
}

const constraints: MediaStreamConstraints = {
  audio: false,
  video: {
    facingMode: 'environment'
  }
};

@Component({
  selector: 'app-camera',
  templateUrl: './camera.component.html',
  styleUrls: ['./camera.component.css']
})
export class CameraComponent implements AfterViewInit {

  public canvasHeight = 720;
  public canvasWidth = 1280;
  public failed = false;
  public loading = true;

  @ViewChild('canvas')
  private canvas: ElementRef<HTMLCanvasElement>;

  public constructor(private cameraService: CameraService, public snackBar: MatSnackBar) { }

  public ngAfterViewInit(): void {
    if (typeof navigator.mediaDevices === 'undefined') {
      this.failed = true;
      this.loading = false;
      this.snackBar.open('Error...', null, { duration: 1000 });

      return;
    }

    const promises = [
      navigator.mediaDevices.getUserMedia(constraints)
        .then(stream => CameraService.loadVideo(stream)),
      this.downloadVideo(environment.overlay.src)
        .then(url => CameraService.loadVideo(url))
      ];

    Promise.all(promises)
      .then(([stream, video]) => {
        this.adjustCanvasSize({
          height: stream.videoHeight,
          width: stream.videoWidth
        });

        this.cameraService.init(this.canvas.nativeElement, stream, video);
        this.loading = false;
      })
      .catch((error) => {
        this.snackBar.open(error.message);
      })
      .finally(() => {
        this.loading = false;
      });
  }

  public onClick(): void {
    const { nativeElement: canvas } = this.canvas;
    const anchor = document.createElement('a');

    let otherTab: Window;

    if (typeof anchor.download !== 'string') {
      otherTab = window.open('assets/logo.png', '_blank');
    }

    canvas.toBlob((blob) => {
      anchor.href = URL.createObjectURL(blob);

      if (!otherTab) {
        anchor.download = `NeruCamera-${Date.now()}.png`;
        anchor.target = '_blank';

        anchor.click();
      } else {
        otherTab.location.href = anchor.href;
      }
    }, 'image/png', 1.0);
  }

  private adjustCanvasSize({ height, width }: CanvasSize): void {
    this.canvasHeight = height;
    this.canvasWidth = width;
  }

  // NOTE: The Service Worker not yet supports a HTTP Range request.
  // Since the video element uses the Range request in many web browsers,
  // it fails fetch via the Service Worker.
  private async downloadVideo(src: string): Promise<string> {
    const req = new Request(src);
    const res = await fetch(req);
    const blob = await res.blob();

    return URL.createObjectURL(blob);
  }
}

<ng-container *ngIf="!failed; then thenBlock; else elseBlock">
</ng-container>

<ng-template #thenBlock>
  <canvas
    #canvas
    class="camera__canvas"
    [height]="canvasHeight"
    [width]="canvasWidth">
  </canvas>
  <div class="camera__action-buttons">
    <button (click)="onClick()" mat-fab>
      <mat-icon aria-label="撮影">photo_camera</mat-icon>
    </button>
  </div>
  <div class="camera__loading" [class.camera__loading--active]="loading">
    <mat-spinner></mat-spinner>
  </div>
</ng-template>

<ng-template #elseBlock>
  <section class="camera__failed mat-typography">
    <h1>カメラの取得に失敗しました</h1>

    <p>あなたの使っているウェブブラウザーはカメラの取得に対応していません。PC の場合、Google Chrome と Firefox 最新版以外での動作は保証できません。Android の場合は Play Store からダウンロードできる Chrome を使ってください。</p>
    <p>また iOS では Safari 以外でカメラの取得ができません。iPhone や iPad を使っている場合は Safari で開き直してください。</p>
  </section>
</ng-template>

// apps/neru-camera/src/components/Camera.vue
<template>
  <div class="camera">
    <div v-if="hasSupportedMediaDevices" class="camera__content">
      <Renderer
        v-if="cameraStream && overlayBlob"
        :camera-stream="cameraStream"
        :overlay-blob="overlayBlob"
        ref="renderer"
      />
    </div>
    <div v-else class="camera__error">
      <h1 class="camera__error__title">カメラの取得に失敗しました</h1>

      <div class="camera__error__body">
        <p class="camera__error__paragraph">
          あなたの使っているアプリはカメラの取得に対応していません。PC
          の場合、Google Chrome と Firefox
          最新版以外での動作は保証できません。Android の場合は Play Store
          からダウンロードできる Chrome を使ってください。
        </p>
        <p class="camera__error__paragraph">
          また iOS では Safari 以外のアプリからカメラの取得ができません。iPhone
          や iPad などの iOS 端末を使っている場合は Safari
          で開き直してください。
        </p>
      </div>
    </div>

    <div class="camera__action-buttons">
      <button
        @click="takePhoto"
        class="camera__action-buttons__button"
        :class="{ 'camera__action-buttons__button--active': isShooting }"
        tabindex="-1"
        title="Take a photo!"
      >
        Take a photo!
      </button>
    </div>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator'

@Component({
  components: {
    Renderer: () => import('@/components/Renderer.vue')
  }
})
export default class extends Vue {
  private cameraStream: MediaStream | null = null
  private isShooting = false
  private overlayBlob: Blob | null = null

  @Prop({ required: true, type: String }) src!: string

  private get hasSupportedMediaDevices() {
    return !!navigator.mediaDevices
  }

  private get mediaStreamConstraints(): MediaStreamConstraints {
    return {
      audio: false,
      video: {
        facingMode: 'environment'
      }
    }
  }

  protected mounted() {
    if (!this.hasSupportedMediaDevices) return

    Promise.all([
      navigator.mediaDevices.getUserMedia(this.mediaStreamConstraints),
      this.download(this.src)
    ]).then(([cameraStream, overlayBlob]) => {
      this.cameraStream = cameraStream
      this.overlayBlob = overlayBlob
    })
  }

  private async download(uri: string): Promise<Blob> {
    const response = await fetch(uri)
    return response.blob()
  }

  private takePhoto(): void {
    const renderer = this.$refs.renderer as any

    if (!renderer) return

    this.isShooting = true

    const anchor = document.createElement('a')

    let otherTab: Window | null
    if (typeof anchor.download !== 'string') {
      otherTab = window.open('about:blank', '_blank')
    }

    renderer
      .toBlob('image')
      .then((blob: Blob | null) => {
        if (!blob) {
          if (otherTab) otherTab.close()

          return
        }

        anchor.href = URL.createObjectURL(blob)

        if (!otherTab) {
          anchor.download = `NeruCamera-${Date.now()}.png`
          anchor.target = '_blank'
          anchor.click()
        } else {
          otherTab.location.href = anchor.href
        }
      })
      .finally(() => {
        this.isShooting = false
      })
  }
}
</script>

<style scoped>
.camera {
  align-items: stretch;
  background-color: #000;
  display: flex;
  flex-direction: column;
  height: 100%;
  justify-content: flex-end;
  margin: 0;
}

.camera__content {
  align-items: center;
  display: flex;
  flex-grow: 1;
  overflow: hidden;
}

.camera__action-buttons {
  background-color: #000;
  box-sizing: border-box;
  display: flex;
  justify-content: space-around;
  padding: 5px 12px 24px;
  width: 100%;
}

.camera__action-buttons__button {
  align-items: center;
  background-color: transparent;
  border: 3px solid #fff;
  border-radius: 50%;
  box-sizing: border-box;
  color: #fff;
  display: block;
  height: 56px;
  overflow: hidden;
  padding: 0;
  width: 56px;
}

.camera__action-buttons__button:focus {
  outline: 0;
}

.camera__action-buttons__button::before {
  background-color: #fff;
  border: 2px solid #000;
  border-radius: 50%;
  box-sizing: border-box;
  content: '';
  display: block;
  height: 100%;
  transition: border-width 0.2s linear;
  width: 100%;
}

.camera__action-buttons__button--active::before {
  border-width: 4px;
}

.camera__error {
  padding: 0.5rem;
}

.camera__error__title {
  font-size: 1.25rem;
  font-weight: 700;
  margin: 0 0 0.5rem 0;
}

.camera__error__paragraph {
  line-height: 1.75;
  margin: 0;
}

.camera__error__paragraph:not(:first-child) {
  margin-top: 1rem;
}
</style>
