// apps/neru-camera/src/components/renderer/renderer.tsx
import { Application, Sprite } from 'pixi.js'
import { Viewport } from 'pixi-viewport'
import React, {
  ReactElement,
  SyntheticEvent,
  forwardRef,
  useCallback,
  useEffect,
  useImperativeHandle,
  useRef,
  useState
} from 'react'
import { Asset } from '../../context/asset-context'
import { ChromaKeyFilter } from '../../filters/ChromaKeyFilter'

export type RefObject = {
  toBlob: (type: string, quality: number) => Promise<Blob>
}

export type Props = {
  asset: Asset
  cameraStream: MediaStream
}

const Renderer = forwardRef<RefObject, Props>(
  ({ asset, cameraStream }, ref): ReactElement => {
    const [viewport, setViewport] = useState<Viewport>()

    const previewRef = useRef<HTMLCanvasElement>(null)
    const cameraRef = useRef<HTMLVideoElement>(null)
    const overlayRef = useRef<HTMLVideoElement>(null)

    const setup = useCallback(
      (event: SyntheticEvent<HTMLVideoElement, Event>) => {
        if (!previewRef.current) return

        const background = Sprite.from(event.currentTarget)

        const app = new Application({
          height: background.height,
          preserveDrawingBuffer: true,
          view: previewRef.current,
          width: background.width
        })
        const viewport = new Viewport({
          interaction: app.renderer.plugins.interaction,
          screenHeight: app.screen.height,
          screenWidth: app.screen.width,
          worldHeight: app.screen.height,
          worldWidth: app.screen.width
        })

        viewport
          .drag()
          .pinch()
          .wheel()
          .decelerate()

        app.stage.addChild(background)
        app.stage.addChild(viewport)

        setViewport(viewport)

        if (overlayRef.current) overlayRef.current.load()
      },
      []
    )

    const handleLoadedData = useCallback(
      (event: SyntheticEvent<HTMLVideoElement, Event>) => {
        if (!viewport) return

        const target = event.currentTarget
        const overlay = Sprite.from(target)
        const { keyColor } = target.dataset

        overlay.filters = [new ChromaKeyFilter(keyColor)]
        overlay.anchor.set(0.5)
        overlay.position.set(
          viewport.worldWidth * 0.5,
          viewport.worldHeight * 0.5
        )

        viewport.addChild(overlay)
      },
      [viewport]
    )

    useEffect(() => {
      if (!cameraRef.current) return

      cameraRef.current.srcObject = cameraStream
    }, [cameraStream])

    useImperativeHandle(ref, () => ({
      toBlob: (type = 'image/png', quality = 1.0): Promise<Blob> =>
        new Promise((resolve, reject): void => {
          if (!previewRef.current) {
            reject(new TypeError('Canvas is not mounted.'))
            return
          }

          const canvas = document.createElement('canvas')
          const context = canvas.getContext('2d')

          canvas.width = previewRef.current.width
          canvas.height = previewRef.current.height

          if (!context) {
            reject(new TypeError('Context does not exist.'))
            return
          }

          try {
            context.drawImage(previewRef.current, 0, 0)
            canvas.toBlob(
              blob => {
                if (!blob) {
                  reject(new TypeError('Blob is empty.'))
                  return
                }

                resolve(blob)
              },
              type,
              quality
            )
          } catch (error) {
            reject(error)
          }
        })
    }))

    return (
      <>
        <div className="renderer">
          <canvas className="renderer__preview" ref={previewRef} />

          <video
            className="renderer__preloaded"
            crossOrigin="anonymouse"
            muted
            onLoadedData={setup}
            playsInline
            ref={cameraRef}
          />
          <video
            className="renderer__preloaded"
            crossOrigin="anonymouse"
            data-key-color={asset.keyColor}
            loop
            muted
            onLoadedData={handleLoadedData}
            playsInline
            preload="none"
            ref={overlayRef}
            src={asset.src}
          />
        </div>

        <style jsx>{`
          .renderer {
            position: relative;
            width: 100%;
          }

          .renderer__preview {
            display: block;
            height: auto;
            width: 100%;
          }

          .renderer__preloaded {
            display: none;
          }
        `}</style>
      </>
    )
  }
)

export default Renderer

// apps/neru-camera/src/components/Renderer.vue
<template>
  <div class="camera-renderer">
    <canvas class="camera-renderer__preview" ref="preview" />

    <pinch-zoom class="dummy" @change="change">
      <div class="dummy__item"></div>
    </pinch-zoom>

    <div class="camera-renderer__preloaded">
      <video
        @loadeddata="setup"
        crossorigin="anonymous"
        muted
        playsinline
        ref="camera"
        :src-object.prop="cameraStream"
      />
      <video
        crossorigin="anonymous"
        preload="none"
        loop
        muted
        playsinline
        ref="overlay"
        :src="asset.src"
      />
    </div>
  </div>
</template>

<script lang="ts">
import PinchZoom from 'pinch-zoom-element'
import { Application, Sprite } from 'pixi.js'
import Vue from 'vue'
import { ChromaKeyFilter } from '@/filters/ChromaKeyFilter'
import { Asset } from '@/store/asset/state'

type Data = {
  overlay?: Sprite
}

type Methods = {
  change: (event: Event) => void
  setup: () => void
  toBlob: () => Promise<Blob | null>
}

type Computed = {
  preview: HTMLCanvasElement
}

type Props = {
  asset: Asset
  cameraStream: MediaStream
}

export default Vue.extend<Data, Methods, Computed, Props>({
  computed: {
    preview() {
      return this.$refs.preview as HTMLCanvasElement
    }
  },

  data() {
    return {
      overlay: undefined
    }
  },

  methods: {
    change(event) {
      if (!this.overlay) return

      const { scale, x, y } = event.target as PinchZoom
      const { clientHeight, clientWidth, height, width } = this.preview

      this.overlay.position.set(
        x * (width / clientWidth) + width / 2,
        y * (height / clientHeight) + height / 2
      )
      this.overlay.scale.set(scale)
    },

    setup() {
      const background = Sprite.from(this.$refs.camera as HTMLVideoElement)

      const app = new Application({
        height: background.height,
        preserveDrawingBuffer: true,
        view: this.preview,
        width: background.width
      })

      app.stage.addChild(background)

      const overlayElement = this.$refs.overlay as HTMLVideoElement
      const onLoadedData = () => {
        overlayElement.removeEventListener('loadeddata', onLoadedData)

        const overlay = Sprite.from(overlayElement)

        overlay.filters = [new ChromaKeyFilter(this.asset.keyColor)]
        overlay.anchor.set(0.5)
        overlay.position.set(app.screen.width * 0.5, app.screen.height * 0.5)

        app.stage.addChild(overlay)

        this.overlay = overlay
      }

      overlayElement.addEventListener('loadeddata', onLoadedData)

      overlayElement.load()
    },

    toBlob(type = 'image/png') {
      return new Promise<Blob | null>((resolve, reject) => {
        const canvas = document.createElement('canvas')
        const context = canvas.getContext('2d')

        if (!context) return resolve(null)

        canvas.height = this.preview.height
        canvas.width = this.preview.width

        try {
          context.drawImage(this.preview, 0, 0)

          canvas.toBlob(resolve, type)
        } catch (error) {
          reject(error)
        }
      })
    }
  },

  props: {
    asset: {
      required: true,
      type: Object
    },
    cameraStream: {
      required: true,
      type: MediaStream
    }
  }
})
</script>

<style scoped>
.camera-renderer {
  position: relative;
  width: 100%;
}

.camera-renderer__preview {
  display: block;
  height: auto;
  width: 100%;
}

.camera-renderer__preloaded {
  display: none;
}

.dummy {
  align-items: center;
  bottom: 0;
  display: flex;
  justify-content: center;
  left: 0;
  position: absolute;
  right: 0;
  top: 0;
}

.dummy__item {
  background-color: transparent;
  height: 1px;
  width: 1px;
}
</style>
